#!/usr/bin/env python3
"""
send-report.py — Cross-platform report email sender for the Dev Skill.

Usage:
    python3 send-report.py <TICKET_KEY> <REPORT_PATH> <FORMAT>

    TICKET_KEY   e.g. IV-3672
    REPORT_PATH  absolute path to the PDF or HTML report file
    FORMAT       "PDF" or "HTML"

Required environment variables (only when PRX_EMAIL_TO is set):
    PRX_EMAIL_TO    recipient address
    PRX_SMTP_HOST   SMTP server hostname  (e.g. smtp.gmail.com)
    PRX_SMTP_USER   SMTP login username
    PRX_SMTP_PASS   SMTP password or app password

Optional:
    PRX_SMTP_PORT   SMTP port (default: 587, STARTTLS)

Exit codes:
    0  email sent (or skipped because PRX_EMAIL_TO is not set)
    1  configuration error or send failure
"""

import os
import sys
import smtplib
from email.message import EmailMessage
from pathlib import Path


def main():
    if len(sys.argv) != 4:
        print("Usage: python3 send-report.py <TICKET_KEY> <REPORT_PATH> <FORMAT>",
              file=sys.stderr)
        sys.exit(1)

    ticket_key = sys.argv[1]
    report_path = Path(sys.argv[2])
    fmt = sys.argv[3].upper()

    email_to = os.environ.get("PRX_EMAIL_TO", "").strip()
    if not email_to:
        print(f"EMAIL_SKIP: PRX_EMAIL_TO not set — skipping email for {ticket_key}")
        sys.exit(0)

    smtp_host = os.environ.get("PRX_SMTP_HOST", "").strip()
    smtp_user = os.environ.get("PRX_SMTP_USER", "").strip()
    smtp_pass = os.environ.get("PRX_SMTP_PASS", "").strip()
    smtp_port = int(os.environ.get("PRX_SMTP_PORT", "587"))

    missing = [v for v, val in [
        ("PRX_SMTP_HOST", smtp_host),
        ("PRX_SMTP_USER", smtp_user),
        ("PRX_SMTP_PASS", smtp_pass),
    ] if not val]

    if missing:
        print(f"EMAIL_ERROR: PRX_EMAIL_TO is set but the following required variables "
              f"are missing: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)

    if not report_path.exists():
        print(f"EMAIL_ERROR: Report file not found: {report_path}", file=sys.stderr)
        sys.exit(1)

    mime_type = "application/pdf" if fmt == "PDF" else "text/html"
    subject = f"[Dev Skill] {ticket_key} Analysis Report"
    body = (
        f"The {fmt} analysis report for {ticket_key} has been attached.\n\n"
        f"Generated by the Dev Skill (Claude Code plugin).\n"
        f"Report file: {report_path.name}\n"
    )

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = email_to
    msg.set_content(body)

    with open(report_path, "rb") as f:
        msg.add_attachment(
            f.read(),
            maintype=mime_type.split("/")[0],
            subtype=mime_type.split("/")[1],
            filename=report_path.name,
        )

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
        print(f"EMAIL_SENT: {ticket_key} report sent to {email_to}")
    except smtplib.SMTPAuthenticationError:
        print(
            f"EMAIL_ERROR: SMTP authentication failed for {smtp_user}. "
            "Check PRX_SMTP_USER and PRX_SMTP_PASS (use an app password for Gmail).",
            file=sys.stderr,
        )
        sys.exit(1)
    except smtplib.SMTPException as e:
        print(f"EMAIL_ERROR: Failed to send email — {e}", file=sys.stderr)
        sys.exit(1)
    except OSError as e:
        print(
            f"EMAIL_ERROR: Cannot connect to {smtp_host}:{smtp_port} — {e}",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
